packages:
  - apps/*
  - packages/*
  - shared/*
  - shared/configs/*
catalog:
  lucide-react: ^0.503.0
  '@tailwindcss/vite': ^4.1.5
catalogs:
  types:
    '@types/node': ^22.15.3
  typescript:
    typescript: ^5.3.8
  react:
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
    react: ^19.1.0
    react-dom: ^19.1.0
  storybook:
    storybook: 9.0.0-beta.10
    '@storybook/react-vite': 9.0.0-beta.10
  playwright:
    playwright: ^1.52.0
    '@playwright/test': ^1.52.0
    '@playwright/experimental-ct-react': ^1.52.0
  vite:
    vite: ^6.3.4
    '@vitejs/plugin-react-swc': ^3.9.0
    vite-tsconfig-paths: ^5.1.4
  vitest:
    vitest: ^3.1.2
    '@vitest/coverage-v8': ^3.1.2
    '@vitest/coverage-istanbul': ^3.1.2
    '@vitest/browser': ^3.1.2
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
