packages:
  - apps/*
  - packages/*
  - shared/*
  - shared/configs/*
catalog:
  lucide-react: ^0.503.0
catalogs:
  types:
    '@types/node': ^22.15.3
  typescript:
    typescript: ^5.3.8
  react:
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
    react: ^19.1.0
    react-dom: ^19.1.0
onlyBuiltDependencies:
  - lefthook
  - sharp
